font_family CaskaydiaCove Nerd Font Mono
font_size   11.0

bold_font        auto
italic_font      auto
bold_italic_font auto

mouse_hide_wait 0.0

window_margin_width 4
window_padding_width 0

cursor_shape_unfocused unchanged
